### ISSUE TITLE
Failed test thread - test thread create with options table

### ISSUE THREAD

**Issue by mcepl** [luvit/luv#473] opened 2020-04-08 12:06 UTC
```
./tests/test-thread.lua:67: bad argument #1 to 'new_thread' (function expected, got table)
  stack traceback:
  	[C]: in function 'new_thread'
  	./tests/test-thread.lua:67: in function 'fn'
  	./lib/tap.lua:53: in function <./lib/tap.lua:42>
  	[C]: in function 'xpcall'
  	./lib/tap.lua:42: in function 'run'
  	./lib/tap.lua:136: in function 'tap'
  	tests/run.lua:33: in main chunk
  	[C]: ?
not ok 68 thread - test thread create with options table
```
While building lua-luv package for openSUSE Leap 15.1 (so, there is no chance of upgrading luv, for example). Is there something which can be done other than just patching out the test?

[Complete build log with all details and versions of packages](https://github.com/luvit/luv/files/4450310/_log.txt)

**Comment by SinisterRectus** [comment] 2020-04-08 12:34
It looks like you are using luv 1.30.1-1 with libuv 1.18.0.

The signature for this call is usually `new_thread(fn, fn)`, but a `new_thread(tbl, fn, fn)` overload was added in 1.26.0. Your test failure appears to be a bug in how we are handling the arguments given that version combination. We either need to add a version check to the test, or always allow but sometimes ignore the table at argument 1.

**Comment by mcepl** [comment] 2020-04-08 12:50
OK, just one brief look at ``src/thread.c`` and I will gladly leave fixing this bug to you ;).

**Comment by squeek502** [comment] 2020-04-11 04:35
Should skip it for Libuv versions that don't support the options table. It's a duplicate of 
https://github.com/luvit/luv/blob/bccba81b9deacf78bf0d7722c97546623ce61e1e/tests/test-thread.lua#L26
just with an options table.

**Closed** 2020-04-13 06:18 UTC
Labels: bug, tests
